#!/bin/sh

palette="/tmp/palette.png"

#x=200
#out_w=600
x=100
out_w=800
filters="crop=$out_w:$out_w:$x:$x,fps=15,scale=320:-1:flags=lanczos"
#"crop=$out_w:$out_w:$x:$x" -gifflags -transdiff -y out.gif


#ffmpeg -v warning -i $1 -vf "$filters,palettegen=stats_mode=diff" -y $palette
ffmpeg -v warning -i $1 -vf "$filters,palettegen=stats_mode=full" -y $palette
ffmpeg -v warning -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
